# Generated by Django 4.2.7 on 2023-11-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_actual_price_product_price_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
