# Generated by Django 4.2.7 on 2023-11-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_banner_link_remove_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
