# Generated by Django 4.2.7 on 2023-11-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='selling_price',
        ),
    ]
