# Generated by Django 4.2.7 on 2023-11-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_price_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
