# Generated by Django 4.2.7 on 2023-11-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_quantity', models.PositiveIntegerField(default=1)),
                ('add_to_cart', models.BooleanField(default=False)),
                ('buy_now', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, related_name='product_images', to='store.productimage')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
