# Generated by Django 4.2.7 on 2023-11-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
