# Generated by Django 4.2.7 on 2023-11-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_variant_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
