# Generated by Django 4.2.7 on 2023-11-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
