# Generated by Django 4.2.7 on 2023-11-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productcolorvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColorVariant',
        ),
    ]
