# Generated by Django 4.2.7 on 2023-11-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_delete_productcolorvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
