# Generated by Django 4.2.7 on 2023-11-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_category_slug_product_variant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
