# Generated by Django 4.2.7 on 2023-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_variant_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='vaiant_main_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_extra_images'),
        ),
    ]
