# Generated by Django 4.2.7 on 2023-11-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_variant_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='extra_images',
        ),
    ]
