# Generated by Django 4.2.7 on 2023-11-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_variant_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
