# Generated by Django 4.2.7 on 2023-11-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
