# Generated by Django 4.2.7 on 2023-11-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_actual_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_selling_price',
        ),
    ]
