# Generated by Django 4.2.7 on 2023-11-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_cart_final_price_cart_total_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_variant'),
        ),
    ]
