# Generated by Django 4.2.7 on 2023-11-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_wishlist_wishitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
