# Generated by Django 4.2.7 on 2023-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_cartitem_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='actual_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
