# Generated by Django 4.2.7 on 2023-11-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_cartitem_actual_price_cartitem_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='selling_price',
        ),
    ]
