# Generated by Django 4.2.7 on 2023-11-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_cartitem_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='actual_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
