# Generated by Django 4.2.7 on 2023-11-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_useraddress'),
        ('store', '0044_checkout_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='core.useraddress'),
        ),
    ]
