# Generated by Django 4.2.7 on 2023-11-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_remove_coupon_coupon_checkout_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=200),
        ),
    ]
