# Generated by Django 4.2.7 on 2023-11-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_checkout_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='cart',
            new_name='cart_item',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
