# Generated by Django 4.2.7 on 2023-11-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_rename_cart_checkout_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='store.cart'),
        ),
    ]
