# Generated by Django 4.2.7 on 2023-11-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_coupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
