# Generated by Django 4.2.7 on 2023-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_coupon_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='coupon',
        ),
        migrations.AddField(
            model_name='checkout',
            name='coupon_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
