# Generated by Django 4.2.7 on 2023-12-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_remove_checkout_coupon_checkout_coupon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
