# Generated by Django 4.2.7 on 2023-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_order_orderitem_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
