# Generated by Django 4.2.7 on 2023-12-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_coupon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='slug',
        ),
    ]
