# Generated by Django 4.2.7 on 2023-12-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_remove_coupon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
