# Generated by Django 4.2.7 on 2023-12-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_order_coupon_discount_order_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
    ]
