# Generated by Django 4.2.7 on 2023-12-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_remove_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
