# Generated by Django 4.2.7 on 2023-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_remove_order_checkout_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
