# Generated by Django 4.2.7 on 2023-12-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_orderitem_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
