# Generated by Django 4.2.7 on 2023-12-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_slug',
        ),
    ]
