# Generated by Django 4.2.7 on 2023-12-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_order_total_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirm'), ('cancelled', 'Cancel'), ('processing', 'Processing'), ('shipping', 'Shipped'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
