# Generated by Django 4.2.7 on 2023-11-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
