# Generated by Django 4.2.7 on 2023-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work')], max_length=20),
        ),
    ]
