# Generated by Django 4.2.7 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_useraddress_landmark_alter_useraddress_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
