# Generated by Django 4.2.7 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_useraddress_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
