# Generated by Django 4.2.7 on 2023-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_useraddress_mobile_alter_useraddress_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
